webServer-v2:http_conn.cpp http_conn.h  threadpool.h webServer-v2.cpp locker.h
	g++ -o webServer-v2 webServer-v2.cpp http_conn.cpp  http_conn.h threadpool.h  locker.h -lpthread 


clean:
	rm  webServer-v2